name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: gcc c_example.c 
    - name: make
      run: ./a.out

name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 4'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Test Action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}